services:
  web:
    image: localhost/reporting_web:latest
    env_file:
      - .env.prod
    ports:
      - 8080:8000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
