services:
  web:
    image: reportingauto:1.0
    command: gunicorn --bind 0.0.0.0:8000 reportingauto.wsgi:application
    env_file:
      - .env.prod
    ports:
      - "8080:8000"
    depends_on:
      - db
      - broker


  celery_worker:
    image: reportingauto:1.0
    command: celery -A reportingauto worker -l INFO
    env_file:
      - .env.prod
    depends_on:
      - web
      - broker

  celery_beat:
    image: reportingauto:1.0
    command: celery -A reportingauto beat -l INFO
    env_file:
      - .env.prod
    depends_on:
      - web
      - broker


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  broker:
    image: redis:7.2.5

volumes:
  postgres_data:



